### ISSUE TITLE
stock nginx configuration misconfigured?

### ISSUE THREAD

**Issue by 0i8** [salad-server/lettuce-web#3]
running a bancho.py instance at https://halcyon.moe, wanted to try this out

running the api in development mode 
![chrome_DaaL2vWV3E](https://user-images.githubusercontent.com/24374615/189033963-67578e3c-c2d7-4766-a1cb-bcf808685e81.png)
leads me to the api on the root domain, where the frontend should be (web.halcyon.moe)

running the api in production mode will eternally redirect until the browser errors out
nginx configuration attached, symlinked as it should be a la the instructions in the readme
https://files.catbox.moe/o7tkqd.conf

**Comment by Cyan903** [comment]
Hey thanks for checking this out. I'm surprised someone stumbled upon this frontend. So I ran though the install on a local VM using your config file and I didn't have any issues. From what I can see, your nginx config looks good to me.

You mentioned the nginx config being symlinked, however the setup doesn't actually include any symlinks. The conf is stored in `/etc/nginx/conf.d`, which is supposed to be the ["newer"](https://stackoverflow.com/a/41568701) method of storing nginx configs.

https://github.com/salad-server/lettuce-web/blob/main/README.md?plain=1#L69

There is a chance that the current frontend you have running is preventing lettuce from running. I'm not sure if this will help, but here are my exact configs that I'm using to run the frontend.

- [config.json](https://pastebin.com/H9RyBRXK)
- [config.yaml](https://pastebin.com/Ce4WzBd9)
- [lettuce.conf](https://pastebin.com/G4wY12XW)

Also, you can find a live version of the server [here](https://hwk929.ca/) (ignore the guy). I also recommend you read [this](https://github.com/salad-server/lettuce-web#differences). If you still can't get it running feel free to pm me or continue the thread. 

Nice server btw. The material design is pretty well done.

**Comment by 0i8** [comment]
i thought it was symlinked, guess not -- however i do have a symlinked nginx configuration in my gulag installation, so i just placed the lettuce stuff there and removed the copy to conf.d

instead of web (frontend) and conn (api) both leading to conn, web now throws a 500 error with nothing in the console to tell me why
i have copied your configuration files as closely as i can

**Comment by 0i8** [comment]
turns out this was a permissions issue

running `sudo tail -f /var/log/nginx/error.log` gave me 
> 2022/09/10 08:15:56 [crit] 147912#147912: *59326 stat() "/home/jupiter/halcyon/lettuce-web/dist/index.html" failed (13: Permission denied), client: 172.71.22.9, server: web.halcyon.moe, request: "GET /favicon.ico HTTP/1.1", host: "web.halcyon.moe", referrer: "https://web.halcyon.moe/"
> 2022/09/10 08:15:56 [error] 147912#147912: *59326 rewrite or internal redirection cycle while internally redirecting to "/index.html", client: 172.71.22.9, server: web.halcyon.moe, request: "GET /favicon.ico HTTP/1.1", host: "web.halcyon.moe", referrer: "https://web.halcyon.moe/"

running `sudo chmod -R o+x /home/halcyon` fixes this issue, and allows the user to connect to the website.
